steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "gcr.io/$PROJECT_ID/stats-importer:latest", "." ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/$PROJECT_ID/stats-importer:latest" ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "stats-importer"
      - "--image=gcr.io/$PROJECT_ID/stats-importer:latest"
      - "--region=europe-west3"
      - "--cpu=2"
      - "--memory=2048Mi"
      - "--timeout=600"
      - "--concurrency=20"
      - "--platform=managed"
      - "--max-instances=100"